title: SOBotics

baseurl: "" # TODO - preferably without breaking anything 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SOBotics
github_username:  SOBotics

# Build settings
markdown: kramdown
theme: minima


### Servers

servers: 
  - "Bhargav Rao/Heroku": {
      Host: "Bhargav Rao",
      Projects: [ 
         "Tag Wiki Edit Monitor": "https://github.com/SOBotics/TagWiki-Monitor"
      ]
    }
  - "Bhargav Rao/Azure": {
      Host: "Bhargav Rao",
      Domain: "us2.sobotics.org",
      Projects: [
          "UserStalker": "https://github.com/SOBotics/UserStalker",
          "JukeBox": "https://github.com/SOBotics/JukeBox",
          "Boson": "https://github.com/SOBotics/Boson",
          "Badger": "https://github.com/SOBotics/Badger"
        ]
    }
  - "BhargavRaoServer": {
    Host: "Bhargav Rao",
    Projects: [
      "Revenant": "https://github.com/SOBotics/Revenant"
    ]
  }
  - "Petter Friberg/WindowsServer2012": {
      Host: "Petter Friberg",
      Projects: [
        "HeatDetector": "https://github.com/SOBotics/HeatDetector",
        "SOCVFinder": "https://github.com/SOBotics/SOCVFinder"
      ]
  }
  - "FelixSFD/eu1.sobotics.org": {
    Host: "FelixSFD",
    Domain: "eu1.sobotics.org",
    Projects: [
      "Guttenberg": "https://github.com/SOBotics/Guttenberg",
      "Notepad": "https://github.com/SOBotics/Notepad"
    ]
  }
  - "FelixSFD/eu2.sobotics.org": {
    Host: "FelixSFD",
    Domain: "eu2.sobotics.org",
    Projects: [
      "Guttenberg": "https://github.com/SOBotics/Guttenberg",
      "CopyPastor": "https://github.com/SOBotics/CopyPastor",
      "Open Reports": "https://github.com/SOBotics/Open-Reports"
    ]
  }
  - "NobodyNada/Raspberry Pi": {
    Host: "NobodyNada",
    Projects: [
      "FireAlarm": "https://github.com/SOBotics/FireAlarm",
      "Reports": "https://github.com/SOBotics/Reports"
    ]
  }
  - "Filnor/Blitz": {
    Host: "Filnor", 
    Projects: [
      "CheckYerFlags": "https://github.com/SOBotics/FlaggersHall",
      "Hermes": "https://github.com/SOBotics/SoundFlow",
      "Thunder": "https://github.com/SOBotics/Thunder"
    ]
  }
  - "FilnorServer": {
    Host: "Filor",
    Domain: "eu3.sobotics.org",
    Projects: [
      "Natty": "https://github.com/SOBotics/Natty",
      "NAPI": "https://github.com/SOBotics/NAPI"
    ]
  }
  - "Floern/Huckepack": {
    Host: "Floern",
    Projects: [
      "Generic Bot": "https://github.com/Floern/stackoverflow"
    ]
  }
  - "FrankerZServer": {
    Host: "FrankerZ",
    Projects: [
      "SpotDetector": "https://github.com/SOBotics/SpotDetector"
    ]
  }
  - "paper1111Server": {
    Host: "paper1111",
    Projects: [
      "Sockite": "https://github.com/SOBotics/Sockite"
    ]
  }
  - "ArtofCodeServer": {
    Host: "Art of Code",
    Projects: [
      "Redunda": "https://github.com/SOBotics/Redunda"
    ]
  }
  - "JoncleServer": {
    Host: "Joncle",
    Projects: [
      "Burnaki": "https://github.com/SOBotics/Burnaki"
    ]
  }
  - "PandyaServer": {
    Host: "Pandya",
    Projects: [
      "CitationDetector": "https://github.com/SOBotics/Citation-Detector"
    ]
  }
  - "RobServer": {
    Host: "Rob",
    Projects: [
      "Rodgort": "https://github.com/SOBotics/Rodgort",
      "Higgs": "https://github.com/SOBotics/Higgs"
    ]
  }
  - "GitHub": {
    Host: "GitHub",
    Projects: [
      "SOBotics Blog": "https://github.com/SOBotics/SOBotics.github.io",
      "SOBotics Team": "https://github.com/SOBotics/Team-Dash"
    ]
  }
  - "BugsServer": {
    Host: "Bugs",
    Projects: [
      "Belisarius": "https://github.com/SOBotics/Belisarius"
    ]
  }

### Contributors
# Pull requests are welcome for this part: I have no clue who to add here.
# Same on coders
contributors: 
  regulars: 
    - geisterfurz007: "https://stackoverflow.com/users/6707985/"
    - "Baum mit Augen": "https://stackoverflow.com/users/3002139/"
    - "Petter Friberg": "https://stackoverflow.com/users/5292302/"
    - "Shree": "https://stackoverflow.com/users/965146"
    - "Floern": "https://stackoverflow.com/users/559745"
    - "Zoe": "https://stackoverflow.com/users/6296561"
    - "Jonathan": "https://stackoverflow.com/users/2263949"
    - "double-beep": "https://stackoverflow.com/users/10607772"
    - "kayess": "https://stackoverflow.com/users/4805174"
    - "Rob": "https://stackoverflow.com/users/3648282"
    - "Bhargav Rao": "https://stackoverflow.com/users/4099593"
    - "Andras Deak": "https://stackoverflow.com/users/5067311"
    - "Yunnosch": "https://stackoverflow.com/users/7733418"
    - "FelixSFD": "https://stackoverflow.com/users/4687348"
    - "Rob": "https://stackoverflow.com/users/563532"
    - "adiga": "https://stackoverflow.com/users/3082296"
    - "Filnor": "https://stackoverflow.com/users/4733879/"
    - "Stephen Kennedy": "https://stackoverflow.com/users/397817/"
    - "NobodyNada": "https://stackoverflow.com/users/3476191"
    - "Ashish Ahuja": "https://stackoverflow.com/users/4688119"
    - "Rai Talha Rehman Khan": "https://stackoverflow.com/users/6727487"
  #coders:

